default_agent: test_voice
agents:
  test_voice:
    name: test_voice
    entrypoint: C:/Users/Admin/Desktop/sarvam/agent/voice1.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\Admin\Desktop\sarvam
    aws:
      execution_role: arn:aws:iam::762233739050:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-91573022fa
      execution_role_auto_create: false
      account: '762233739050'
      region: ap-south-1
      ecr_repository: 762233739050.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-test_voice
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
